"""T3 — Reserved By / Test Name columns populate correctly while a
testbed is active.

Confirmed by exploration: the dashboard's Port Status table shows
Reserved By "test (you)" for a port reserved directly via its own
Reserve button, but the Test Name column stays "—" for that kind of
plain reservation. Test Name only populates once a testbed is actually
activated (Apply — "Save & activate on the unit") — and it populates
immediately on activation, before ever clicking Start, so this doesn't
need to generate real traffic or wait for a run to finish, just
Apply/deactivate.
"""
import pytest
from playwright.sync_api import Page, expect

NAME = "T3-ActiveColumns-DeleteMe"
PORTS = ["Port 1", "Port 2"]


def _testbed_tile(page: Page):
    return page.locator(".tb-tile").filter(has_text=NAME)


def _delete_testbed_if_present(page: Page):
    tile = _testbed_tile(page)
    if tile.count() > 0:
        tile.locator('[data-tip="Delete"] button').click()
        page.get_by_role("button", name="Delete", exact=True).click()
        expect(_testbed_tile(page)).to_have_count(0, timeout=10000)


def _release_ports(page: Page):
    dashboard_btn = page.get_by_role("button", name="← Dashboard")
    if dashboard_btn.is_visible():
        dashboard_btn.click()
        page.wait_for_timeout(400)
        discard_btn = page.get_by_role("button", name="Discard", exact=True)
        if discard_btn.is_visible():
            discard_btn.click()
    else:
        page.goto("/")
    expect(page.get_by_text("Port Status")).to_be_visible(timeout=20000)
    for port_label in PORTS:
        row = page.get_by_role("row", name=port_label)
        release_btn = row.get_by_role("button", name="Release")
        if release_btn.is_visible():
            release_btn.click()
            confirm = page.get_by_role("button", name="Deactivate & release")
            if confirm.is_visible():
                confirm.click()
            expect(row.get_by_text("Available", exact=True)).to_be_visible(timeout=10000)


@pytest.fixture
def clean_testbed(dashboard: Page):
    _delete_testbed_if_present(dashboard)
    yield
    _release_ports(dashboard)
    _delete_testbed_if_present(dashboard)


@pytest.mark.stateful
def test_t3_reserved_by_and_test_name_populate_on_activation(
    dashboard: Page, clean_testbed
):
    page = dashboard

    for port_label in PORTS:
        row = page.get_by_role("row", name=port_label)
        expect(row.get_by_text("Available", exact=True)).to_be_visible()

    page.get_by_role("button", name="✚ Create Testbed", exact=True).click()
    page.get_by_placeholder("e.g. web-perf-01").fill(NAME)
    page.get_by_role("button", name="Traffic Engine", exact=True).click()
    page.get_by_role("button", name="Create draft", exact=True).click()
    tile = _testbed_tile(page)
    expect(tile).to_have_count(1, timeout=10000)
    tile.get_by_role("button", name="Edit").click()
    expect(page.get_by_role("heading", name="Ports", exact=False).first).to_be_visible(
        timeout=15000
    )
    row1 = page.locator("tr").nth(1)
    row2 = page.locator("tr").nth(2)
    row1.locator(".toggle .track").click()
    row2.locator(".toggle .track").click()

    page.get_by_role("button", name="3 Streams", exact=False).click()
    expect(page.get_by_role("button", name="✚ Add Stream", exact=True)).to_be_visible(
        timeout=10000
    )
    page.get_by_role("button", name="✚ Add Stream", exact=True).click()
    expect(page.get_by_role("button", name="Add stream", exact=True)).to_be_visible(
        timeout=10000
    )
    page.get_by_role("button", name="Add stream", exact=True).click()

    # Apply reserves the ports at the engine and populates Test Name —
    # this happens on activation itself, before Start; no traffic is
    # ever generated by this test.
    page.get_by_role("button", name="Apply", exact=True).click()
    expect(page.get_by_role("button", name="Deactivate")).to_be_visible(timeout=75000)

    page.get_by_role("button", name="← Dashboard").click()
    discard_btn = page.get_by_role("button", name="Discard", exact=True)
    if discard_btn.is_visible():
        discard_btn.click()
    expect(page.get_by_text("Port Status")).to_be_visible(timeout=10000)

    for port_label in PORTS:
        row = page.get_by_role("row", name=port_label)
        expect(row.get_by_text("Reserved", exact=True)).to_be_visible()
        expect(row).to_contain_text("test (you)")
        # The Test Name column truncates in the DOM itself (not just
        # visually via CSS) — confirmed "T3-ActiveColumns-DeleteMe" comes
        # through as "T3-ActiveColumn" (15 chars), so match a prefix.
        expect(row).to_contain_text(NAME[:15])
